### PR TITLE
Numpy json serializer

### PR DESCRIPTION
**Pull request by glamp**
Extension of simplejson that provides a Yhat json module that can serialize numpy specific objects (np.nan, np.array).

This will get put in the python kernel and will look something like this:

```
try:
    from yhat import yhat_json as __json
except ImportError as e:
    import json as __json
```

### CODE REVIEW

**Comment by rosskipp** [comment]
This looks good 👍  Just need to finalize the naming

**Comment by glamp** [comment]
Some options:
- GSuite
- Quickster

**Comment by glamp** [comment]
For reference, going with `from yhat import simplejson`. The reason being it is simplejson. We've just added a few enhancements to it which the "from yhat" part indicates that it’s yhat’s own simplejson.

**Comment by rosskipp** [comment]
Tests pass! Looks good 👍

**Pull request merged**
